name: Gerar App iOS (IPA)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Motor Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false
        
    - name: Preparar Mutacao do Pacote Go
      run: |
        mkdir -p mobile
        cp main.go mobile/mobile.go
        cp -r static mobile/
        cp -r templates_teste mobile/
        cp equipamentos.json mobile/
        sed -i '' 's/package main/package mobile/g' mobile/mobile.go
        sed -i '' 's/func main()/func StartServer()/g' mobile/mobile.go
        cd mobile
        go mod init mobile
        
    - name: Instalar Ferramentas Apple
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        export PATH=$PATH:$(go env GOPATH)/bin
        gomobile init
        brew install xcodegen
        
    - name: Compilar Motor Offline (.xcframework)
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        cd mobile
        go get golang.org/x/mobile/bind
        gomobile bind -target=ios -o ../ios/Mobile.xcframework .
        
    - name: Gerar App Xcode
      working-directory: ios
      run: xcodegen generate
        
    - name: Montar Arquivo .ipa (Bypass de Assinatura)
      working-directory: ios
      run: |
        # A MÁGICA AQUI: Forçando a pasta de saída do Xcode
        xcodebuild build -project FibraApp.xcodeproj -scheme FibraApp -configuration Release -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CONFIGURATION_BUILD_DIR=$PWD/build
        mkdir -p Payload
        mv build/FibraApp.app Payload/
        zip -r FibraApp.ipa Payload
        
    - name: Guardar Instalador Final
      uses: actions/upload-artifact@v4
      with:
        name: Instalador-iPhone-IPA
        path: ios/FibraApp.ipa
